server:
  port: 8085

spring:
  datasource:
    password: 217812.com #数据库用户名
    username: root #数据库密码
    url: jdbc:mysql://localhost:3306/obtain-employee?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: oauth
          uri: localhost:8081
          predicates:
            - Path=/oauth/**
#          filters:
#            -
        - id: user
          uri: localhost:8080
          predicates:
            - Path=/user/**
        - id: company
          uri: localhost:8082
          predicates:
            - Path=/company/**

